import { sql } from "drizzle-orm";
import { bigint, timestamp, uuid } from "drizzle-orm/pg-core";

/** Standard UUID primary key generated by Postgres. */
export const idColumn = () =>
  uuid("id")
    .primaryKey()
    .default(sql`gen_random_uuid()`);

/** Money is always an integer count of cents (spec section 31.2). */
export const centsColumn = (name: string) => bigint(name, { mode: "number" }).notNull();

export const createdAtColumn = () =>
  timestamp("created_at", { withTimezone: true }).notNull().defaultNow();

export const updatedAtColumn = () =>
  timestamp("updated_at", { withTimezone: true }).notNull().defaultNow();
